import { LangCode } from "./languages";

export interface IntentPattern {
  keywords: RegExp[];
  intent: string;
  priority: number;
}

export interface IntentResponse {
  [lang: string]: string | undefined;
}

export function getResponse(lang: LangCode, intent: string): string {
  const responses: Record<string, IntentResponse> = {
    greeting: {
      en: "Hello! I'm Cornelius Maina Nyaga's AI assistant. I can tell you about his skills, projects, experience, and how to get in touch. What would you like to know?",
      sw: "Habari! Mimi ni msaidizi wa AI wa Cornelius Maina Nyaga. Ninaweza kukueleza kuhusu ujuzi wake, miradi, uzoefu, na jinsi ya kuwasiliana. Ungependa kujua nini?",
      fr: "Bonjour! Je suis l'assistant IA de Cornelius Maina Nyaga. Je peux vous renseigner sur ses competences, projets, experience et comment le contacter. Que souhaitez-vous savoir?",
      es: "Hola! Soy el asistente IA de Cornelius Maina Nyaga. Puedo contarte sobre sus habilidades, proyectos, experiencia y como contactarlo. Que te gustaria saber?",
      de: "Hallo! Ich bin der KI-Assistent von Cornelius Maina Nyaga. Ich kann dir uber seine Fahigkeiten, Projekte, Erfahrung und Kontakt erzahlen. Was moechtest du wissen?",
      ru: "Privet! Ya pomoshchnik AI Corneliusa Maina Nyagi. Ya mogu rasskazat o yevo navykakh, proektakh, opyte i kak s nim svyazatsya. Chto vy khotite uznat?",
      zh: "Ni hao! Wo shi Cornelius Maina Nyaga de AI zhushou. Wo keyi gaosu nin guanyu ta de jineng, xiangmu, jingyan, he ruzi lianxi ta. Nin xiang liaojie shenme?",
      ja: "Konnichiwa! Cornelius Maina Nyaga no AI assistanto desu. Skill, project, keiken, oyobi renraku houhou ni tsuite oshieru koto ga dekimasu. Nani wo shiritai deshou ka?",
      ko: "Annyeonghaseyo! Cornelius Maina Nyaga-ui AI bugeo-ibnida. Gi-su, project, gyeong-heom, yeollak bangsik-e daehae al-lyeodeurigessseubnida. Museun geol algo siposeyo?",
      ar: "Marhaba! Ana musa'ad al-istina'i li-Cornelius Maina Nyaga. yumkinuni an akhbaruakum 'an mahratihi, mawaridihi, tajribatihi, wa kayfa yatasalu ma'ahu. Matha turid an ta'lam?",
      hi: "Namaste! Main Cornelius Maina Nyaga ka AI sahayak hun. Main aapko unke skills, projects, experience, aur unse kaise sampark karein ke baare mein bata sakta hun. Aap kya janna chahenge?",
      tr: "Merhaba! Cornelius Maina Nyaga'nin AI asistaniyim. Onun becerileri, projeleri, deneyimi ve nasil iletisime gececeginiz hakkinda bilgi verebilirim. Ne ogrenmek istersiniz?",
      pt: "Ola! Sou o assistente IA de Cornelius Maina Nyaga. Posso contar sobre suas habilidades, projetos, experiencia e como entrar em contato. O que voce gostaria de saber?",
      it: "Ciao! Sono l'assistente IA di Cornelius Maina Nyaga. Posso parlarti delle sue competenze, progetti, esperienza e come contattarlo. Cosa vorresti sapere?",
      nl: "Hallo! Ik ben de AI-assistent van Cornelius Maina Nyaga. Ik kan je vertellen over zijn vaardigheden, projecten, ervaring en hoe contact op te nemen. Wat wil je weten?",
      pl: "Czesc! Jestem asystentem AI Corneliusa Mainy Nyagi. Moge powiedziec o jego umiectnosciach, projektach, doswiadczeniu i jak sie skontaktowac. Co chcesz wiedziec?",
      uk: "Privit! Ya pomichnyk AI Corneliusa Maina Nyagi. Ya mozhu rozkazaty pro yoho navychky, proekty, dosvid i yak z nim zvyazatisya. Shcho vy khotite dovidatisya?",
      th: "Sawatdee! Chan pen AI chuai khun rueang Cornelius Maina Nyaga. Chan len kan hai phuak khun ruu rueang skill, project, pramuan kan, lae kan toet-sam. Araya yang khun son-ja pai-ja?",
      vi: "Xin chao! Toi la tro ly AI cua Cornelius Maina Nyaga. Toi co the cho ban biet ve ky nang, du an, kinh nghiem va cach lien he. Ban muon tim hieu gi?",
      id: "Halo! Saya adalah asisten AI Cornelius Maina Nyaga. Saya bisa memberi tahu Anda tentang keterampilannya, proyek, pengalaman, dan cara menghubunginya. Apa yang ingin Anda ketahui?",
      ms: "Halo! Saya adalah pembantu AI Cornelius Maina Nyaga. Saya boleh memberitahu anda tentang kemahirannya, projek, pengalaman, dan cara menghubunginya. Apa yang anda ingin tahu?",
      tl: "Kamusta! Ako ang AI assistant ni Cornelius Maina Nyaga. Masasabi ko sa iyo ang tungkol sa kanyang mga kasanayan, proyekto, karanasan, at paano siya makontak. Ano ang gusto mong malaman?",
      sv: "Hej! Jag ar Cornelius Maina Nyagas AI-assistent. Jag kan beratta om hans fardigheter, projekt, erfarenhet och hur man kontakter honom. Vad vill du veta?",
      no: "Hei! Jeg er Cornelius Maina Nyagas AI-assistent. Jeg kan fortelle om hans ferdigheter, prosjekter, erfaring og hvordan kontakte ham. Hva vil du vite?",
      da: "Hej! Jeg er Cornelius Maina Nyagas AI-assistent. Jeg kan fortelle om hans fardigheder, projekter, erfaring og hvordan man kontakter ham. Hvad vil du vide?",
      fi: "Hei! Olen Cornelius Maina Nyagan AI-avustaja. Voin kertoa hanen taidoistaan, projekteistaan, kokemuksistaan ja miten ottaa yhteytta. Mitä haluat tietaa?",
      so: "Salaan! Waxaan ahay caawiyaha AI ee Cornelius Maina Nyaga. Waxaan ku siin karaa macluumaad ku saabsan xirfadihiisa, mashaariicdiisa, khibradiisa, iyo sida loo xiriiriyo. Maxaad rabtaa inaad ogaato?",
      am: "Selam! Ena Cornelius Maina Nyaga AI makedasqwe eya negn. Maleshalew new amet maresawot new kefeetaw, sasatatew, sir awal new eye yezet new demetk new ale? Ki new eye kefalew newem?",
    },
    about: {
      en: "Cornelius Maina Nyaga is a Full-Stack Developer and Cybersecurity Expert based in Kenya. He's the founder of TIXSYNC SOLUTIONS and TIXSYNC Media, specializing in building secure, scalable systems.\n\n**Key Facts**:\n- Based in Kenya, serving clients across Africa\n- Full-Stack Development: React, Next.js, TypeScript, Node.js, Python\n- Cybersecurity: Penetration Testing, SOC, Security Architecture\n- Cloud Architecture: AWS, Azure\n- DevOps and System Administration\n\nHis mission is to protect and empower businesses through technology.",
      sw: "Cornelius Maina Nyaga ni Msanidi Programu wa Kamili na Mtaalamu wa Ulinzi wa Mtandao aliye maskani yake Kenya. Yeye ndiye mwanzilishi wa TIXSYNC SOLUTIONS na TIXSYNC Media, maalum katika kujenga mifumo salama, inayoweza kupanuliwa.\n\n**Uhalisia Muhimu**:\n- Maskani yake Kenya, anayehudumia wateja kote Afrika\n- Uundaji Kamili: React, Next.js, TypeScript, Node.js, Python\n- Ulinzi wa Mtandao: Majaribio ya Uvamizi, SOC, Usanidi wa Usalama\n- Usanidi wa Wingu: AWS, Azure\n- DevOps na Usimamizi wa Mifumo\n\nDhamira yake ni kulinda na kuwezesha biashara kupitia teknolojia.",
      fr: "Cornelius Maina Nyaga est un Developpeur Full-Stack et Expert en Cybersecurite base au Kenya. Il est le fondateur de TIXSYNC SOLUTIONS et TIXSYNC Media, specialise dans la construction de systemes securises et evolutifs.\n\n**Faits cles**:\n- Base au Kenya, servant des clients a travers l'Afrique\n- Developpement Full-Stack: React, Next.js, TypeScript, Node.js, Python\n- Cybersecurite: Tests de Penetration, SOC, Architecture Securite\n- Architecture Cloud: AWS, Azure\n- DevOps et Administration Systeme\n\nSa mission est de proteger et d'autonomiser les entreprises grace a la technologie.",
      es: "Cornelius Maina Nyaga es un Desarrollador Full-Stack y Experto en Ciberseguridad con sede en Kenia. Es el fundador de TIXSYNC SOLUTIONS y TIXSYNC Media, especializado en construir sistemas seguros y escalables.\n\n**Datos clave**:\n- Con sede en Kenia, atendiendo clientes en toda Africa\n- Desarrollo Full-Stack: React, Next.js, TypeScript, Node.js, Python\n- Ciberseguridad: Pruebas de Penetracion, SOC, Arquitectura de Seguridad\n- Arquitectura Cloud: AWS, Azure\n- DevOps y Administracion de Sistemas\n\nSu mision es proteger y empoderar a las empresas a traves de la tecnologia.",
      de: "Cornelius Maina Nyaga ist ein Full-Stack-Entwickler und Cybersicherheitsexperte mit Sitz in Kenia. Er ist Grunder von TIXSYNC SOLUTIONS und TIXSYNC Media, spezialisiert auf den Aufbau sicherer, skalierbarer Systeme.\n\n**Wichtige Fakten**:\n- Sitz in Kenia, bedient Kunden in ganz Afrika\n- Full-Stack-Entwicklung: React, Next.js, TypeScript, Node.js, Python\n- Cybersicherheit: Penetrationstests, SOC, Sicherheitsarchitektur\n- Cloud-Architektur: AWS, Azure\n- DevOps und Systemadministration\n\nSeine Mission ist es, Unternehmen durch Technologie zu schutzen und zu starken.",
      ru: "Cornelius Maina Nyaga - full-stack razrabotchik i ekspert po kiberbezopasnosti iz Kenii. Osnovatel TIXSYNC SOLUTIONS i TIXSYNC Media, spetsializiruyetsya na sozdanii bezopasnykh i maskhtabiruyemykh sistem.\n\n**Osnovnyye fakty**:\n- Baziruyetsya v Kenii, obsluzhivayet klientov po vsey Afrike\n- Full-stack razrabotka: React, Next.js, TypeScript, Node.js, Python\n- Kiberbezopasnost: Pentesty, SOC, arkhitektura bezopasnosti\n- Oblachnaya arkhitektura: AWS, Azure\n- DevOps i sistemnoye administrirovaniye\n\nYego missiya - zashchishchat i usilit biznes cherez tekhnologii.",
      zh: "Cornelius Maina Nyaga shi yiwu quanzhan kaifa zhe he wangluo anquan zhuanjia, zhazha zai Kenniya. Ta shi TIXSYNC SOLUTIONS he TIXSYNC Media de chuangshiren, zhuanzhu yu goujian anquan, ke kuozhan de xitong.\n\n**Guanyuan shixiang**:\n- Zongbu zai Kenniya, fuwu Feizhou gedi kehu\n- Quanzhan kaifa: React, Next.js, TypeScript, Node.js, Python\n- Wangluo anquan: Shentou ceshi, SOC, Anquan jiagou\n- Yun jiagou: AWS, Azure\n- DevOps he xitong guanli\n\nTa de shiming shi tongguo jishu baohu he shengneng qiye.",
      ja: "Cornelius Maina Nyaga wa Kenya wo kichito suru full-stack kaihatsusha de saibaeru sekyuriti senmonka desu. TIXSYNC SOLUTIONS to TIXSYNC Media no soshikisha de, an'nei de sukeeraburu na shisetsu no kochiku wo senmon to shimasu.\n\n**Daiji na koto**:\n- Kenya ni kichi wo oki, Afrika zentai ni kyuukyaku wo tsutawarimasu\n- Full-stack kaihatsu: React, Next.js, TypeScript, Node.js, Python\n- Saibaeru sekyuriti: Penetreesyon tesuto, SOC, sekyuriti aahekitekucha\n- Kuraudo aahekitekucha: AWS, Azure\n- DevOps to shisetsu kanri\n\nKare no missaihon wa gijutsu wo tsukatte bijinesu wo hogo to juyou suru koto desu.",
    },
    skills: {
      en: "Cornelius is proficient in a wide range of technologies:\n\n**Development**:\n- Frontend: React, Next.js, TypeScript, Tailwind CSS\n- Backend: Node.js, Python, Express, REST APIs, GraphQL\n- Databases: PostgreSQL, MongoDB, Redis\n- Mobile: React Native, Flutter\n\n**Security**:\n- Penetration Testing, SOC Operations\n- Security Architecture, Incident Response\n- SIEM, Firewalls, Vulnerability Assessments\n\n**Infrastructure**:\n- Cloud: AWS, Azure, GCP\n- DevOps: Docker, Kubernetes, CI/CD, Terraform\n- System Administration: Linux, Windows Server\n\n**Other**:\n- Digital Transformation Consulting\n- Compliance (ISO 27001, GDPR)\n- Technical Writing and Documentation",
      sw: "Cornelius ni mtaalamu katika teknolojia nyingi:\n\n**Uundaji**:\n- Mbele: React, Next.js, TypeScript, Tailwind CSS\n- Nyuma: Node.js, Python, Express, REST APIs, GraphQL\n- Hifadhidata: PostgreSQL, MongoDB, Redis\n- Simu: React Native, Flutter\n\n**Ulinzi**:\n- Majaribio ya Uvamizi, Operesheni za SOC\n- Usanidi wa Usalama, Mshughulikiajo wa Matukio\n- SIEM, Motoa, Tathmini za Upvu\n\n**Miundombinu**:\n- Wingu: AWS, Azure, GCP\n- DevOps: Docker, Kubernetes, CI/CD, Terraform\n- Usimamizi wa Mifumo: Linux, Windows Server\n\n**Nyingine**:\n- Ushauri wa Mabadiliko ya Dijitali\n- Uzingatiaji (ISO 27001, GDPR)\n- Uandishi wa Kiufundi",
      fr: "Cornelius maitrise un large eventail de technologies :\n\n**Developpement**:\n- Frontend: React, Next.js, TypeScript, Tailwind CSS\n- Backend: Node.js, Python, Express, REST APIs, GraphQL\n- Bases de donnees: PostgreSQL, MongoDB, Redis\n- Mobile: React Native, Flutter\n\n**Securite**:\n- Tests de Penetration, Operations SOC\n- Architecture Securite, Reponse aux Incidents\n- SIEM, Pare-feu, Evaluations de Vulnerabilite\n\n**Infrastructure**:\n- Cloud: AWS, Azure, GCP\n- DevOps: Docker, Kubernetes, CI/CD, Terraform\n- Administration Systeme: Linux, Windows Server\n\n**Autres**:\n- Conseil en Transformation Numerique\n- Conformite (ISO 27001, GDPR)\n- Redaction Technique",
      es: "Cornelius domina una amplia gama de tecnologias:\n\n**Desarrollo**:\n- Frontend: React, Next.js, TypeScript, Tailwind CSS\n- Backend: Node.js, Python, Express, REST APIs, GraphQL\n- Bases de datos: PostgreSQL, MongoDB, Redis\n- Movil: React Native, Flutter\n\n**Seguridad**:\n- Pruebas de Penetracion, Operaciones SOC\n- Arquitectura de Seguridad, Respuesta a Incidentes\n- SIEM, Firewalls, Evaluaciones de Vulnerabilidad\n\n**Infraestructura**:\n- Nube: AWS, Azure, GCP\n- DevOps: Docker, Kubernetes, CI/CD, Terraform\n- Administracion de Sistemas: Linux, Windows Server\n\n**Otros**:\n- Consultoria en Transformacion Digital\n- Cumplimiento (ISO 27001, GDPR)\n- Redaccion Tecnica",
      de: "Cornelius beherrscht eine breite Palette von Technologien:\n\n**Entwicklung**:\n- Frontend: React, Next.js, TypeScript, Tailwind CSS\n- Backend: Node.js, Python, Express, REST APIs, GraphQL\n- Datenbanken: PostgreSQL, MongoDB, Redis\n- Mobile: React Native, Flutter\n\n**Sicherheit**:\n- Penetrationstests, SOC-Operationen\n- Sicherheitsarchitektur, Incident Response\n- SIEM, Firewalls, Schwachstellenbewertungen\n\n**Infrastruktur**:\n- Cloud: AWS, Azure, GCP\n- DevOps: Docker, Kubernetes, CI/CD, Terraform\n- Systemadministration: Linux, Windows Server\n\n**Sonstiges**:\n- Digital Transformationsberatung\n- Compliance (ISO 27001, GDPR)\n- Technisches Schreiben",
    },
    projects: {
      en: "Cornelius has built various impressive projects:\n\n**Notable Projects**:\n- **TIXSYNC SOLUTIONS**: Enterprise cybersecurity and web development platform\n- **TIXSYNC Media**: Digital media and content platform\n- **Enterprise Web Applications**: Full-stack business solutions\n- **Security Tools**: Penetration testing and vulnerability assessment tools\n- **Cloud Infrastructure**: Scalable cloud deployments\n- **Mobile Applications**: Cross-platform apps using React Native and Flutter\n\nCheck the Projects section of this portfolio for detailed showcases, or visit his GitHub at github.com/PixelCode254.",
      sw: "Cornelius amejenga miradi mbalimbali ya kushangaza:\n\n**Miradi Mashuhuri**:\n- **TIXSYNC SOLUTIONS**: Jukwaa la ulinzi wa mtandao na uundaji wa wavuti\n- **TIXSYNC Media**: Jukwaa la dijitali na maudhui\n- **Programu za Biashara**: Suluhisho kamili za biashara\n- **Zana za Usalama**: Zana za majaribio ya uvamizi na tathmini ya upvu\n- **Miundombinu ya Wingu**: Uwekaji wa wingu unaopanuliwa\n- **Programu za Simu**: Programu za mezani kwa React Native na Flutter\n\nAngalia sehemu ya Miradi ya portfolio hii kwa maonyesho ya kina, au tembelea GitHub yake.",
      fr: "Cornelius a realise divers projets impressionnants :\n\n**Projets Notables**:\n- **TIXSYNC SOLUTIONS**: Plateforme entreprise de cybersecurite et developpement web\n- **TIXSYNC Media**: Plateforme de media numerique et de contenu\n- **Applications Web d'entreprise**: Solutions business full-stack\n- **Outils de Securite**: Outils de tests de penetration et d'evaluation de vulnerabilite\n- **Infrastructure Cloud**: Deploiements cloud evolutifs\n- **Applications Mobiles**: Applications multiplateformes avec React Native et Flutter\n\nConsultez la section Projets de ce portfolio pour des presentations detaillees, ou visitez son GitHub.",
      es: "Cornelius ha construido varios proyectos impresionantes:\n\n**Proyectos Destacados**:\n- **TIXSYNC SOLUTIONS**: Plataforma empresarial de ciberseguridad y desarrollo web\n- **TIXSYNC Media**: Plataforma de medios digitales y contenido\n- **Aplicaciones Web Empresariales**: Soluciones business full-stack\n- **Herramientas de Seguridad**: Herramientas de pruebas de penetracion y evaluacion de vulnerabilidades\n- **Infraestructura en la Nube**: Despliegues en la nube escalables\n- **Aplicaciones Moviles**: Apps multiplataforma con React Native y Flutter\n\nConsulta la seccion de Proyectos de este portafolio para presentaciones detalladas, o visita su GitHub.",
      de: "Cornelius hat verschiedene beeindruckende Projekte realisiert:\n\n**Bemerkenswerte Projekte**:\n- **TIXSYNC SOLUTIONS**: Unternehmensplattform fur Cybersicherheit und Webentwicklung\n- **TIXSYNC MEDIA**: Digitale Medien- und Inhaltsplattform\n- **Enterprise Webanwendungen**: Full-Stack-Geschaftslasungen\n- **Sicherheitstools**: Penetrationstests und Schwachstellenbewertungstools\n- **Cloud-Infrastruktur**: Skalierbare Cloud-Bereitstellungen\n- **Mobile Anwendungen**: Plattformubergreifende Apps mit React Native und Flutter\n\nSchauen Sie sich den Projektbereich dieses Portfolios fur detaillierte Prasentationen an, oder besuchen Sie sein GitHub.",
      ru: "Cornelius sozdal raznoobraznye vпечатel'nyye proekty:\n\n**Zamechatel'nyye proekty**:\n- **TIXSYNC SOLUTIONS**: Korporativnaya platforma kiberbezopasnosti i veb-razrabotki\n- **TIXSYNC Media**: Platforma cifrovykh media i kontenta\n- **Enterprise Veb-prilozheniya**: Full-stack biznes-resheniya\n- **Instrumenty bezopasnosti**: Instrumenty pentesta i otsenki uyazvimostey\n- **Oblachnaya infrastruktura**: Maskhtabiruyemyye oblachnyye razvertyvaniya\n- **Mobil'nyye prilozheniya**: Krossplatformennyye prilozheniya na React Native i Flutter\n\nPosmotrite razdel Portfolio dlya podrobnykh prezentatsiy ili posetite yevo GitHub.",
    },
    hire: {
      en: "To hire Cornelius, please use the contact form on this website or reach out at:\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Phone/WhatsApp**: +254704440164\n\nHe's available for:\n- Freelance projects\n- Consulting engagements\n- Full-time opportunities\n- Security audits and assessments\n- Web and mobile development projects\n\nHe typically responds within 24 hours.",
      sw: "Kwa kuajiri Cornelius, tafadhali fomu ya mawasiliano ya tovuti hii au wasiliana:\n\n- **Barua pepe**: tixsyncsolutions@gmail.com\n- **Simu/WhatsApp**: +254704440164\n\nYupo kwaajiriwa:\n- Miradi ya freelancer\n- Ushauri\n- Fursa za muda wote\n- Ukaguzi na tathmini za usalama\n- Miradi ya uundaji wa wavuti na simu\n\nKawaida hujibu ndani ya masaa 24.",
      fr: "Pour engager Cornelius, veuillez utiliser le formulaire de contact de ce site ou le contacter a :\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Telephone/WhatsApp**: +254704440164\n\nIl est disponible pour :\n- Projets freelance\n- Missions de conseil\n- Opportunites a temps plein\n- Audits et evaluations de securite\n- Projets de developpement web et mobile\n\nIl repond generalement en 24 heures.",
      es: "Para contratar a Cornelius, usa el formulario de contacto de este sitio web o contactalo en:\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Telefono/WhatsApp**: +254704440164\n\nEsta disponible para:\n- Proyectos freelance\n- Consultorias\n- Oportunidades a tiempo completo\n- Auditorias y evaluaciones de seguridad\n- Proyectos de desarrollo web y movil\n\nGeneralmente responde dentro de 24 horas.",
      de: "Um Cornelius zu beauftragen, nutzen Sie bitte das Kontaktformular dieser Website oder kontaktieren Sie ihn unter:\n\n- **E-Mail**: tixsyncsolutions@gmail.com\n- **Telefon/WhatsApp**: +254704440164\n\nEr steht zur Verfugung fur:\n- Freelance-Projekte\n- Beratungsauftrage\n- Vollzeitmoglichkeiten\n- Sicherheitsaudits und Bewertungen\n- Web- und Mobile-Entwicklungsprojekte\n\nEr antwortet in der Regel innerhalb von 24 Stunden.",
    },
    contact: {
      en: "You can reach Cornelius through multiple channels:\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Phone/WhatsApp**: +254704440164\n- **GitHub**: github.com/PixelCode254\n- **Website**: tixsyncsolutions.com\n\nHe responds to all inquiries within 24 hours. For urgent matters, calling or WhatsApp is recommended.",
      sw: "Unaweza kuwasiliana na Cornelius kupitia njia nyingi:\n\n- **Barua pepe**: tixsyncsolutions@gmail.com\n- **Simu/WhatsApp**: +254704440164\n- **GitHub**: github.com/PixelCode254\n- **Tovuti**: tixsyncsolutions.com\n\nHujibu maswali yote ndani ya masaa 24. Kwa mambo ya dharura, inapendekeza kupiga simu au WhatsApp.",
      fr: "Vous pouvez contacter Cornelius par plusieurs canaux :\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Telephone/WhatsApp**: +254704440164\n- **GitHub**: github.com/PixelCode254\n- **Site web**: tixsyncsolutions.com\n\nIl repond a toutes les demandes dans les 24 heures. Pour les urgences, il est recommande d'appeler ou d'utiliser WhatsApp.",
      es: "Puedes contactar a Cornelius a traves de multiples canales:\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Telefono/WhatsApp**: +254704440164\n- **GitHub**: github.com/PixelCode254\n- **Sitio web**: tixsyncsolutions.com\n\nResponde a todas las consultas dentro de 24 horas. Para asuntos urgentes, se recomienda llamar o usar WhatsApp.",
      de: "Sie konnen Cornelius uber mehrere Kanale erreichen:\n\n- **E-Mail**: tixsyncsolutions@gmail.com\n- **Telefon/WhatsApp**: +254704440164\n- **GitHub**: github.com/PixelCode254\n- **Webseite**: tixsyncsolutions.com\n\nEr beantwortet alle Anfragen innerhalb von 24 Stunden. Fur dringende Angelegenheiten wird empfohlen, anzurufen oder WhatsApp zu nutzen.",
    },
    web: {
      en: "Cornelius specializes in building modern web applications:\n\n- **Frontend**: React, Next.js, TypeScript, Tailwind CSS\n- **Backend**: Node.js, Python, Express, REST APIs, GraphQL\n- **Databases**: PostgreSQL, MongoDB, Redis\n- **Specialties**: E-commerce, SaaS, corporate websites, progressive web apps\n\nHis web solutions are built for performance, scalability, and security following modern best practices.",
      sw: "Cornelius maalum katika kujenga programu za wavuti za kisasa:\n\n- **Mbele**: React, Next.js, TypeScript, Tailwind CSS\n- **Nyuma**: Node.js, Python, Express, REST APIs, GraphQL\n- **Hifadhidata**: PostgreSQL, MongoDB, Redis\n- **Maarifa**: E-commerce, SaaS, tovuti za kampuni, programu za hatua za pembeni\n\nSuluhisho zake za wavuti zimejengwa kwa utendaji, kupanuka, na usalama kwa kufuata mazoea bora ya kisasa.",
      fr: "Cornelius se specialise dans le developpement d'applications web modernes :\n\n- **Frontend**: React, Next.js, TypeScript, Tailwind CSS\n- **Backend**: Node.js, Python, Express, REST APIs, GraphQL\n- **Bases de donnees**: PostgreSQL, MongoDB, Redis\n- **Specialites**: E-commerce, SaaS, sites d'entreprise, applications web progressives\n\nSes solutions web sont concues pour la performance, l'evolutivite et la securite.",
      es: "Cornelius se especializa en construir aplicaciones web modernas:\n\n- **Frontend**: React, Next.js, TypeScript, Tailwind CSS\n- **Backend**: Node.js, Python, Express, REST APIs, GraphQL\n- **Bases de datos**: PostgreSQL, MongoDB, Redis\n- **Especialidades**: E-commerce, SaaS, sitios web corporativos, aplicaciones web progresivas\n\nSus soluciones web estan construidas para rendimiento, escalabilidad y seguridad.",
      de: "Cornelius ist spezialisiert auf den Aufbau moderner Webanwendungen:\n\n- **Frontend**: React, Next.js, TypeScript, Tailwind CSS\n- **Backend**: Node.js, Python, Express, REST APIs, GraphQL\n- **Datenbanken**: PostgreSQL, MongoDB, Redis\n- **Spezialgebiete**: E-Commerce, SaaS, Unternehmenswebsites, Progressive Web Apps\n\nSeine Weblosungen sind fur Leistung, Skalierbarkeit und Sicherheit gebaut.",
    },
    security: {
      en: "Cornelius is a cybersecurity expert with deep knowledge in:\n\n- **Penetration Testing**: Finding vulnerabilities before attackers do\n- **SOC Operations**: 24/7 security monitoring and threat detection\n- **Security Architecture**: Designing secure systems from the ground up\n- **Incident Response**: Rapid response to security breaches\n- **SIEM**: Security Information and Event Management\n- **Vulnerability Assessments**: Regular security scanning\n\nHe helps organizations identify and mitigate security risks across Africa.",
      sw: "Cornelius ni mtaalamu wa ulinzi wa mtandao wenye ujuzi wa kina katika:\n\n- **Majaribio ya Uvamizi**: Kutambua upvu kabla ya waovamizi\n- **Operesheni za SOC**: Ufuatiliaji wa usalama 24/7 na utambuzi wa vitisho\n- **Usanidi wa Usalama**: Kupanga mifumo salama tangu mwanzo\n- **Mshughulikiajo wa Matukio**: Majibu ya haraka kwa ukiukaji wa usalama\n- **SIEM**: Usimamizi wa Taarifa za Usalama na Matukio\n- **Tathmini za Upvu**: Uchunguzi wa kawaida wa usalama\n\nAnawasaidia mashirika kutambua na kupunguza hatari za usalama kote Afrika.",
      fr: "Cornelius est un expert en cybersecurite avec de solides connaissances en :\n\n- **Tests de Penetration** : Trouver les vulnerabilites avant les attaquants\n- **Operations SOC** : Surveillance de securite 24h/24 et detection des menaces\n- **Architecture Securite** : Concevoir des systemes securises des le depart\n- **Reponse aux Incidents** : Reponse rapide aux violations de securite\n- **SIEM** : Gestion des informations et evenements de securite\n- **Evaluations de Vulnerabilite** : Analyse reguliere de securite\n\nIl aide les organisations a identifier et mitiger les risques de securite a travers l'Afrique.",
      es: "Cornelius es un experto en ciberseguridad con profundos conocimientos en:\n\n- **Pruebas de Penetracion**: Encontrar vulnerabilidades antes que los atacantes\n- **Operaciones SOC**: Monitoreo de seguridad 24/7 y deteccion de amenazas\n- **Arquitectura de Seguridad**: Disenar sistemas seguros desde cero\n- **Respuesta a Incidentes**: Respuesta rapida a violaciones de seguridad\n- **SIEM**: Gestion de informacion y eventos de seguridad\n- **Evaluaciones de Vulnerabilidad**: Escaneo regular de seguridad\n\nAyuda a las organizaciones a identificar y mitigar riesgos de seguridad en toda Africa.",
      de: "Cornelius ist ein Cybersicherheitsexperte mit tiefem Wissen in:\n\n- **Penetrationstests**: Schwachstellen finden, bevor Angreifer es tun\n- **SOC-Operationen**: 24/7-Sicherheitsuberwachung und Bedrohungserkennung\n- **Sicherheitsarchitektur**: Sichere Systeme von Grund auf entwerfen\n- **Incident Response**: Schnelle Reaktion auf Sicherheitsverletzungen\n- **SIEM**: Security Information and Event Management\n- **Schwachstellenbewertungen**: Regelmassige Sicherheits-Scans\n\nEr hilft Organisationen, Sicherheitsrisiken in ganz Afrika zu identifizieren und zu mindern.",
    },
    tech: {
      en: "Here's a deep dive into Cornelius's technical expertise:\n\n**Programming Languages**: JavaScript, TypeScript, Python, HTML5, CSS3, SQL\n**Frameworks**: React, Next.js, Node.js, Express, Django, Flask\n**Databases**: PostgreSQL, MongoDB, Redis, MySQL\n**Cloud**: AWS (EC2, S3, Lambda), Azure, GCP\n**DevOps**: Docker, Kubernetes, GitHub Actions, Jenkins, Terraform, Ansible\n**Security Tools**: Metasploit, Nmap, Burp Suite, Wireshark, OWASP ZAP\n**Operating Systems**: Linux (Ubuntu, CentOS, Kali), Windows Server\n**Mobile**: React Native, Flutter, Swift, Kotlin",
      sw: "Hii ni mandhari ya kina ya utaalamu wa kiufundi wa Cornelius:\n\n**Lugha za Programu**: JavaScript, TypeScript, Python, HTML5, CSS3, SQL\n**Mifumo**: React, Next.js, Node.js, Express, Django, Flask\n**Hifadhidata**: PostgreSQL, MongoDB, Redis, MySQL\n**Wingu**: AWS (EC2, S3, Lambda), Azure, GCP\n**DevOps**: Docker, Kubernetes, GitHub Actions, Jenkins, Terraform, Ansible\n**Zana za Usalama**: Metasploit, Nmap, Burp Suite, Wireshark, OWASP ZAP\n**Mifumo ya Uendeshaji**: Linux (Ubuntu, CentOS, Kali), Windows Server\n**Simu**: React Native, Flutter, Swift, Kotlin",
    },
    tixsync: {
      en: "TIXSYNC SOLUTIONS is Cornelius's company, providing enterprise-grade:\n\n- **Cybersecurity Services**: Penetration testing, SOC, security audits\n- **Web Development**: Modern, scalable web applications\n- **Cloud Infrastructure**: AWS, Azure, GCP solutions\n- **Digital Transformation**: Business process automation\n- **Compliance**: ISO 27001, GDPR\n- **DevOps**: CI/CD, infrastructure as code\n- **Mobile Development**: React Native, Flutter apps\n\nBased in Kenya, serving clients across Africa. Contact: tixsyncsolutions@gmail.com",
      sw: "TIXSYNC SOLUTIONS ni kampuni ya Cornelius, inatoa kiwango cha biashara:\n\n- **Huduma za Ulinzi wa Mtandao**: Majaribio ya uvamizi, SOC, ukaguzi wa usalama\n- **Uundaji wa Vavuti**: Programu za wavuti za kisasa, zinazopanuliwa\n- **Miundombinu ya Wingu**: Suluhisho za AWS, Azure, GCP\n- **Mabadiliko ya Dijitali**: Uboreshaji wa michakato ya biashara\n- **Uzingatiaji**: ISO 27001, GDPR\n- **DevOps**: CI/CD, miundombinu kama kanuni\n- **Uundaji wa Simu**: Programu za React Native, Flutter\n\nImewekwa Kenya, inayohudumia wateja kote Afrika. Wasiliana: tixsyncsolutions@gmail.com",
    },
    fallback: {
      en: "That's a great question! While I may not have a specific answer for that, I'd recommend reaching out to Cornelius directly at tixsyncsolutions@gmail.com or using the contact form. Is there anything specific about his skills or experience I can help with?",
      es: "Buena pregunta! Te recomiendo contactar a Cornelius directamente en tixsyncsolutions@gmail.com o usar el formulario de contacto. Hay algo especifico sobre sus habilidades en lo que pueda ayudarte?",
      fr: "Excellente question ! Je vous recommande de contacter Cornelius directement a tixsyncsolutions@gmail.com ou d'utiliser le formulaire de contact. Puis-je vous aider avec quelque chose de specifique ?",
      de: "Das ist eine tolle Frage! Ich empfehle, Cornelius direkt unter tixsyncsolutions@gmail.com zu kontaktieren oder das Kontaktformular zu nutzen. Kann ich Ihnen bei etwas Bestimmtem helfen?",
      sw: "Hiyo ni swali zuri! Ingawa sina jibu maalum kwa hilo, ningependekeza kuwasiliana na Cornelius moja kwa moja kwa tixsyncsolutions@gmail.com au kutumia fomu ya mawasiliano. Kuna chochote maalum kuhusu ujuzi wake au uzoefu ambao ninaweza kukusaidia?",
      ru: "Otlichnyy vopros! Rekomenduyu svyazat'sya s Corneliusom napryamuyu: tixsyncsolutions@gmail.com ili cherez formu svyazi. Mogu li ya pomoch' s chem-to konkretnym o yevo navykakh ili opyte?",
      zh: "Zheshige hen hao de wenti! Jianyi zhijie lianxi Cornelius: tixsyncsolutions@gmail.com huoshi shiyong lianxi biaodan. Guanyu ta de jineng huoshi jingyan, you shenme juti de wenti wo keyi bangnin ma?",
      ja: "Ii goshitsumon desu ne! Cornelius ni chokusetsu tixsyncsolutions@gmail.com de renraku suru ka, renraku foramu wo go riyou kudasai. Kare no skill ya keiken ni kanshite, nani ka gutaiteki ni otetsudai dekiru koto wa arimasu ka?",
      ko: "Joeun jilmun-ibnida! Cornelius-ge tuxisilho tixsyncsolutions@gmail.com-ulo yeollak hagesio ilen yeollak yangsik-eul sayonghaseyo. Gi-su na gyeong-heom-e daehae bonaen bugeon-e doweol su isseoyo?",
      ar: "Suan ratib! Anuhuka bil-tawasul ma'a Cornelius mubasharatan ala tixsyncsolutions@gmail.com aw istikhdam namudhaj al-ittisal. Hal min shay' mukhtas bi-maharatih aw khibratihi yumkinuni musa'adatukum bihi?",
      hi: "Bahut accha sawal hai! Meri salah hai ki Cornelius se seedha tixsyncsolutions@gmail.com par sampark karein ya sampark form ka upyog karein. Unki skills ya experience ke baare mein koi vishisht prashn hai jismein main madad kar sakta hun?",
      tr: "Bu harika bir soru! Cornelius'a dogrudan tixsyncsolutions@gmail.com adresinden ulasmanizi veya iletisim formunu kullanmanizi oneririm. Becerileri veya deneyimi hakkinda yardimci olabilecegim bir sey var mi?",
      pt: "Otima pergunta! Recomendo entrar em contato diretamente com Cornelius em tixsyncsolutions@gmail.com ou usar o formulario de contato. Ha algo especifico sobre suas habilidades ou experiencia em que eu possa ajudar?",
      it: "Ottima domanda! Consiglio di contattare Cornelius direttamente a tixsyncsolutions@gmail.com o di usare il modulo di contatto. C'e qualcosa di specifico sulle sue competenze o esperienza in cui posso aiutare?",
    },
    thanks: {
      en: "You're welcome! Feel free to reach out anytime at tixsyncsolutions@gmail.com. Have a great day!",
      sw: "Karibu! Usisite kuwasiliana wakati wowote kwa tixsyncsolutions@gmail.com. Uwe na siku njema!",
      fr: "De rien! N'hesitez pas a nous contacter a tout moment a tixsyncsolutions@gmail.com. Excellente journee!",
      es: "De nada! No dudes en contactarnos en cualquier momento en tixsyncsolutions@gmail.com. Que tengas un excelente dia!",
      de: "Gern geschehen! Kontaktieren Sie uns jederzeit unter tixsyncsolutions@gmail.com. Einen schonen Tag noch!",
    },
    help: {
      en: "I can help you learn about:\n\n- **About Cornelius**: His background, mission, and company\n- **Skills**: Full-Stack Development, Cybersecurity, Cloud, DevOps\n- **Projects**: Enterprise web apps, security tools, cloud solutions\n- **Hire Cornelius**: Freelance, consulting, or full-time opportunities\n- **Contact**: Email, phone, or social media\n\nWhat would you like to know?",
      sw: "Ninaweza kukusaidia kujifunza kuhusu:\n\n- **Kuhusu Cornelius**: Usuli wake, dhamira, na kampuni yake\n- **Ujuzi**: Uundaji Kamili, Ulinzi wa Mtandao, Wingu, DevOps\n- **Miradi**: Programu za wavuti za biashara, zana za usalama, suluhisho za wingu\n- **Kuajiri Cornelius**: Freelancer, ushauri, au fursa za muda wote\n- **Mawasiliano**: Barua pepe, simu, au mitandao ya kijamii\n\nUngependa kujua nini?",
    },
    portfolio: {
      en: "Cornelius's portfolio showcases his work in full-stack development and cybersecurity. Check the Projects section for detailed case studies, or visit his GitHub at github.com/PixelCode254 for open-source contributions.",
      sw: "Portfolio ya Cornelion inaonyesha kazi yake katika uundaji kamili na ulinzi wa mtandao. Angalia sehemu ya Miradi kwa masomo ya kina, au tembelea GitHub yake.",
      fr: "Le portfolio de Cornelius presente son travail en developpement full-stack et cybersecurite. Consultez la section Projets pour des etudes de cas detaillees, ou visitez son GitHub.",
      es: "El portafolio de Cornelius muestra su trabajo en desarrollo full-stack y ciberseguridad. Consulta la seccion de Proyectos para estudios de caso detallados, o visita su GitHub.",
      de: "Cornelius' Portfolio zeigt seine Arbeit in Full-Stack-Entwicklung und Cybersicherheit. Schauen Sie sich den Projektbereich fur detaillierte Fallstudien an, oder besuchen Sie sein GitHub.",
    },
  };

  const response = responses[intent];
  if (!response) return responses.fallback?.en || "Feel free to ask about Cornelius's skills, projects, or how to get in touch.";
  return response[lang] || response.en || responses.fallback?.en || "Feel free to ask about Cornelius's skills, projects, or how to get in touch.";
}

export const INTENT_PATTERNS: IntentPattern[] = [
  { intent: "greeting", priority: 10, keywords: [/\b(hello|hi|hey|good morning|good afternoon|good evening|howdy|whats up|sup)\b/i] },
  { intent: "thanks", priority: 10, keywords: [/\b(thanks?|thank you|bye|goodbye|see you|cheers|appreciate)\b/i] },
  { intent: "help", priority: 9, keywords: [/\b(help|what can|how|what do you|assist|support)\b/i] },
  { intent: "hire", priority: 8, keywords: [/\b(hire|employment|job|freelance|contract|consulting|work with|available|recruit|opportunity)\b/i] },
  { intent: "contact", priority: 8, keywords: [/\b(contact|email|phone|reach|get in touch|call|whatsapp|message)\b/i] },
  { intent: "about", priority: 8, keywords: [/\b(about|who|founder|cornelius|company|story|background|history|mission|introduce|tell me about)\b/i] },
  { intent: "skills", priority: 7, keywords: [/\b(skill|skilled|proficient|expertise|technology|tech stack|languages?|frameworks?|programming|code)\b/i] },
  { intent: "projects", priority: 7, keywords: [/\b(project|portfolio|work|code|github|built|created|showcase|application|app)\b/i] },
  { intent: "web", priority: 7, keywords: [/\b(web\s*(dev|develop|development)|react|next\.?js|node\.?js|typescript|python|full.?stack|website|web app|frontend|backend)\b/i] },
  { intent: "security", priority: 7, keywords: [/\b(security|cybersecurity|penetration|soc|firewall|siem|incident|vulnerability|hack|breach|protect)\b/i] },
  { intent: "tech", priority: 6, keywords: [/\b(tech|technology|stack|tools|aws|azure|docker|kubernetes|linux|database|sql|mongodb|redis)\b/i] },
  { intent: "tixsync", priority: 6, keywords: [/\b(tixsync|solution|company|business|venture|media)\b/i] },
  { intent: "portfolio", priority: 6, keywords: [/\b(portfolio|resume|cv|work showcase)\b/i] },
];

export function matchIntent(text: string): { intent: string; priority: number } {
  const lower = text.toLowerCase();
  let best = { intent: "fallback", priority: 0 };
  for (const pattern of INTENT_PATTERNS) {
    if (pattern.priority <= best.priority) continue;
    for (const keyword of pattern.keywords) {
      if (keyword.test(lower)) {
        best = { intent: pattern.intent, priority: pattern.priority };
        break;
      }
    }
  }
  return best;
}
